### ISSUE TITLE
Python 3 support

### ISSUE THREAD

**Issue by aztennenbaum** [NationalSecurityAgency/lemongraph#12]
Python 2 is reaching its end of life in 2020, which is not far off.

**Comment by NSA-LGDev2** [comment]
Concur, but no immediate plans to do so.

**Comment by impredicative** [comment]
@NSA-LGDev2 As you musy know, Python 2 is scheduled for expiration in approximately 1.5 years which is not far at all. This calls for a plan to make the move.

**Comment by cclauss** [comment]
Converting __buffer()__ into __memoryview()__ in __./LemonGraph/httpd.py__ is key to this transition if anyone is willing to take that on.

**Comment by NSA-LGDev2** [comment]
Please enjoy some freshly baked Python 3 support! 2705b299a1c76195b307d494bdea45a533550a47

**Comment by impredicative** [comment]
@NSA-LGDev2 That's great. The readme still contains:

> The core of the graph library is written in C, and the Python (2.x) 

Can the readme be updated?

**Comment by NSA-LGDev2** [comment]
Done - thanks!
