### ISSUE TITLE
lg-lite branch status

### ISSUE THREAD

**Issue by d4tocchini** [NationalSecurityAgency/lemongraph#25]
`lg-lite` seems to compile & function properly, any details / status on this branch?  Should this be viewed this as preferred direction moving forward or experimental not likely to be merged?

**Comment by NSA-LGDev2** [comment]
Yes, `lg-lite` will get pushed to master at some point. I need to decide if tasks should have additional states and if so, how best to structure that. At the moment, tasks are either pending, or do not exist. It might be useful to be able to mark a task as completed (or errored?), and optionally retain original task contents. Thoughts are welcome!

**Comment by d4tocchini** [comment]
I'll check it out, thanks

**Comment by d4tocchini** [comment]
on a related note, can you clarify how multi-threading / processes fits in with tasks?  

In the lg-lite branch, is the REST service the same structure: with a master proc, sync proc and potential worker req-handler procs?  

Thinking about it, task state, other than completed or not, is probably best left to task-specific concerns, right?  A task could always hit the disk or mutate shared memory systemV style or whatever.   I don't see needing more than stateless configuration for things like job priority, how worker-threads match with job-types, locking worker-threads to processors, etc.  A solid example in this area being Naughty Dog Engine's fiber-based task scheduler [see Christian Gyrling GDC Talk](http://gdcvault.com/play/1022186/Parallelizing-the-Naughty-Dog-Engine).  Potentially usable implementation [here](https://github.com/septag/sx/blob/master/include/sx/jobs.h).

**Comment by NSA-LGDev2** [comment]
Sure - `tasks` have nothing to do with threads/processes - they are a batch of records from a single job that were pulled by an adapter client. If you haven't yet, take a look [here](https://github.com/NationalSecurityAgency/lemongraph/blob/lg-lite/LG_LITE.md#lg-lite) - that explains the purpose of the `lg-lite` branch.

Same process topology for the web service though - master proc, sync proc, and multiple web workers.

**Comment by d4tocchini** [comment]
I probably should've digested that doc more as I was clearly conflating the concept of tasks with jobs and hypothetical job execution concerns.  I think a high level overview from input through internals to output with tangible use-cases would help me & prob others better contribute here.  Flushing out the Design section of LG_LITE.md and sprinkling a few sample code-blocks would likely suffice.  Obviously, understanding can be gleamed in the tests, examples and source, but @ayende's [7-part lemongraph code-review](https://ayende.com/blog/posts/series/184066-C/reading-the-nsas-codebase) sheds light on such an attempt.  

Thanks for clarifying the status of the lg-lite branch.  I'll close this issue & if I land on tangible insights or conceptual-blocks regarding tasks & the like I'll open a PR to help move the docs along.
